name: ci
on:
  push:
    branches:
      - master
jobs:
  docker:
    env:
      TAG: v3.4.4-patched
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Clone Mastodon
        run: |
          git clone https://github.com/kgtkr/mastodon.git -b $TAG --depth 1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: mastodon
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mastodon-docker:${{ env.TAG }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
